/**
 * axe-fingerprints.ts — the committed, machine-checkable axe baseline.
 *
 * GENERATED FILE. Do not hand-edit individual entries; regenerate instead.
 *
 * One entry per cell of the measurement matrix (`viewport|theme|tab`), holding
 * every axe violating node as a `rule ID :: normalized target` fingerprint,
 * deduplicated and sorted.
 *
 * Regenerate:
 *   MDF_AXE_BASELINE_WRITE=1 npm run test:browser
 *   node e2e/baseline/regenerate.mjs > e2e/baseline/axe-fingerprints.ts
 *
 * A regenerated file is byte-identical when nothing changed, so an unexpected
 * diff here is itself the signal.
 *
 * The key set is pinned too, not just the fingerprints: axe.spec.ts asserts that
 * these keys are exactly the measured matrix, so a missing cell and a stale
 * leftover cell both fail the run.
 *
 * See known-violations.ts for what each rule means and which PR owns it.
 */

export const AXE_FINGERPRINTS: Record<string, string[]> = {
  '360x812|dark|all': [
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface-overlay.border-edge.p-4 > .items-start.gap-3.flex > .border-primary.mt-\\[2px\\].w-\\[22px\\]',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .bg-surface-overlay.border-edge.p-4 > .items-start.gap-3.flex > .border-primary.mt-\\[2px\\].w-\\[22px\\]',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(3) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(4) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(7) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(9) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .w-\\[46px\\]',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(1) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(3) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(4) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .text-fg-disabled',
    'color-contrast :: .text-primary.tracking-tight.text-\\[11px\\]',
    'color-contrast :: .text-primary\\/80',
    'label :: .\\[color-scheme\\:dark\\]',
    'label :: .text-\\[24px\\]',
    'select-name :: select',
  ],
  '360x812|dark|done': [
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .mt-\\[2px\\].w-\\[22px\\].h-\\[22px\\]',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .mt-\\[2px\\].w-\\[22px\\].h-\\[22px\\]',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(7) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(9) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .w-\\[46px\\]',
    'color-contrast :: .gap-1.py-1.transition-colors:nth-child(1) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .gap-1.py-1.transition-colors:nth-child(2) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .gap-1.py-1.transition-colors:nth-child(3) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .mt-1.flex-wrap.gap-2 > .text-\\[11\\.5px\\].text-fg-meta.gap-1\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .items-start.gap-2.flex > .leading-relaxed.break-words.py-0\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .mt-1.flex-wrap.gap-2 > .text-\\[11\\.5px\\].text-fg-meta.gap-1\\.5',
    'color-contrast :: .text-primary.tracking-tight.text-\\[11px\\]',
    'label :: .text-\\[24px\\]',
    'select-name :: select',
  ],
  '360x812|dark|today': [
    'button-name :: .overflow-hidden.rounded-2xl.relative:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(7) > .mb-6.justify-between.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(9) > .mb-6.justify-between.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .w-\\[46px\\]',
    'button-name :: section:nth-child(1) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'button-name :: section:nth-child(2) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'button-name :: section:nth-child(3) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'color-contrast :: .line-through.text-blue-400.opacity-70',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(2) > .text-\\[11px\\].text-fg-faint.tracking-tight',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(3) > .text-\\[11px\\].text-fg-faint.tracking-tight',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(4) > .text-\\[11px\\].text-fg-faint.tracking-tight',
    'color-contrast :: .text-primary.text-\\[11px\\].tracking-tight',
    'label :: .text-\\[24px\\]',
    'select-name :: select',
  ],
  '360x812|light|all': [
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface-overlay.border-edge.p-4 > .items-start.gap-3.flex > .border-primary.mt-\\[2px\\].w-\\[22px\\]',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .bg-surface-overlay.border-edge.p-4 > .items-start.gap-3.flex > .border-primary.mt-\\[2px\\].w-\\[22px\\]',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(3) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(4) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(7) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(9) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .w-\\[46px\\]',
    'color-contrast :: .group\\/ci.text-left.gap-2:nth-child(1) > .text-fg-meta.text-\\[11\\.5px\\].leading-relaxed',
    'color-contrast :: .line-clamp-2',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-rose-300\\/90.bg-rose-500\\/10.text-\\[10px\\]',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-rose-300\\/90.bg-rose-500\\/10.text-\\[10px\\]',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(3) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(4) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(1) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(3) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(4) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .text-fg-disabled',
    'color-contrast :: .text-primary\\/80',
    'label :: .\\[color-scheme\\:dark\\]',
    'label :: .text-\\[24px\\]',
    'select-name :: select',
  ],
  '360x812|light|done': [
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .mt-\\[2px\\].w-\\[22px\\].h-\\[22px\\]',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .mt-\\[2px\\].w-\\[22px\\].h-\\[22px\\]',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(7) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(9) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .w-\\[46px\\]',
    'color-contrast :: .gap-1.py-1.transition-colors:nth-child(1) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .gap-1.py-1.transition-colors:nth-child(2) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .gap-1.py-1.transition-colors:nth-child(3) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .mt-1.flex-wrap.gap-2 > .text-\\[11\\.5px\\].text-fg-meta.gap-1\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .items-start.gap-2.flex > .leading-relaxed.break-words.py-0\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .mt-1.flex-wrap.gap-2 > .text-\\[11\\.5px\\].text-fg-meta.gap-1\\.5',
    'label :: .text-\\[24px\\]',
    'select-name :: select',
  ],
  '360x812|light|today': [
    'button-name :: .overflow-hidden.rounded-2xl.relative:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(7) > .mb-6.justify-between.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(9) > .mb-6.justify-between.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .w-\\[46px\\]',
    'button-name :: section:nth-child(1) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'button-name :: section:nth-child(2) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'button-name :: section:nth-child(3) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'color-contrast :: .gap-1.flex-col.flex > .text-\\[12px\\].text-slate-400.font-medium',
    'color-contrast :: .line-through.text-blue-400.opacity-70',
    'color-contrast :: .overflow-hidden.rounded-2xl.relative:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-rose-300\\/90.bg-rose-500\\/10.px-1\\.5',
    'color-contrast :: .overflow-hidden.rounded-2xl.relative:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: .overflow-hidden.rounded-2xl.relative:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-rose-300\\/90.bg-rose-500\\/10.px-1\\.5',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(2) > .text-\\[11px\\].text-fg-faint.tracking-tight',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(3) > .text-\\[11px\\].text-fg-faint.tracking-tight',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(4) > .text-\\[11px\\].text-fg-faint.tracking-tight',
    'color-contrast :: .text-slate-200',
    'color-contrast :: section:nth-child(1) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: section:nth-child(1) > .mb-3.gap-2\\.5.items-center > .items-baseline.gap-2\\.5.flex > .text-\\[12px\\].text-slate-400.font-medium',
    'color-contrast :: section:nth-child(2) > .mb-3.gap-2\\.5.items-center > .items-baseline.gap-2\\.5.flex > .text-\\[12px\\].text-slate-400.font-medium',
    'label :: .text-\\[24px\\]',
    'select-name :: select',
  ],
  '390x812|dark|all': [
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface-overlay.border-edge.p-4 > .items-start.gap-3.flex > .border-primary.mt-\\[2px\\].w-\\[22px\\]',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .bg-surface-overlay.border-edge.p-4 > .items-start.gap-3.flex > .border-primary.mt-\\[2px\\].w-\\[22px\\]',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(3) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(4) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(7) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(9) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .w-\\[46px\\]',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface-overlay.border-edge.p-4 > .items-start.gap-3.flex > .opacity-50.min-w-0.flex-1 > .items-start.gap-2.flex > .text-slate-400.decoration-slate-500.line-through',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(1) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(3) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(4) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .text-fg-disabled',
    'color-contrast :: .text-primary.tracking-tight.text-\\[11px\\]',
    'color-contrast :: .text-primary\\/80',
    'label :: .\\[color-scheme\\:dark\\]',
    'label :: .text-\\[24px\\]',
    'select-name :: select',
  ],
  '390x812|dark|done': [
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .mt-\\[2px\\].w-\\[22px\\].h-\\[22px\\]',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .mt-\\[2px\\].w-\\[22px\\].h-\\[22px\\]',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(7) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(9) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .w-\\[46px\\]',
    'color-contrast :: .gap-1.py-1.transition-colors:nth-child(1) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .gap-1.py-1.transition-colors:nth-child(2) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .gap-1.py-1.transition-colors:nth-child(3) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .items-start.gap-2.flex > .leading-relaxed.break-words.py-0\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .mt-1.flex-wrap.gap-2 > .text-\\[11\\.5px\\].text-fg-meta.gap-1\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .items-start.gap-2.flex > .leading-relaxed.break-words.py-0\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .mt-1.flex-wrap.gap-2 > .text-\\[11\\.5px\\].text-fg-meta.gap-1\\.5',
    'color-contrast :: .text-primary.tracking-tight.text-\\[11px\\]',
    'label :: .text-\\[24px\\]',
    'select-name :: select',
  ],
  '390x812|dark|today': [
    'button-name :: .overflow-hidden.rounded-2xl.relative:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(7) > .mb-6.justify-between.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(9) > .mb-6.justify-between.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .w-\\[46px\\]',
    'button-name :: section:nth-child(1) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'button-name :: section:nth-child(2) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'button-name :: section:nth-child(3) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'color-contrast :: .line-through.text-blue-400.opacity-70',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(2) > .text-\\[11px\\].text-fg-faint.tracking-tight',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(3) > .text-\\[11px\\].text-fg-faint.tracking-tight',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(4) > .text-\\[11px\\].text-fg-faint.tracking-tight',
    'color-contrast :: .text-primary.text-\\[11px\\].tracking-tight',
    'color-contrast :: .text-primary\\/80',
    'label :: .text-\\[24px\\]',
    'select-name :: select',
  ],
  '390x812|light|all': [
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface-overlay.border-edge.p-4 > .items-start.gap-3.flex > .border-primary.mt-\\[2px\\].w-\\[22px\\]',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .bg-surface-overlay.border-edge.p-4 > .items-start.gap-3.flex > .border-primary.mt-\\[2px\\].w-\\[22px\\]',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(3) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(4) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(7) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(9) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .w-\\[46px\\]',
    'color-contrast :: .group\\/ci.text-left.gap-2:nth-child(1) > .text-fg-meta.text-\\[11\\.5px\\].leading-relaxed',
    'color-contrast :: .line-clamp-2',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface-overlay.border-edge.p-4 > .items-start.gap-3.flex > .opacity-50.min-w-0.flex-1 > .items-start.gap-2.flex > .text-slate-400.decoration-slate-500.line-through',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-rose-300\\/90.bg-rose-500\\/10.text-\\[10px\\]',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-rose-300\\/90.bg-rose-500\\/10.text-\\[10px\\]',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(3) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(4) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(1) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(3) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(4) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .text-fg-disabled',
    'color-contrast :: .text-primary\\/80',
    'label :: .\\[color-scheme\\:dark\\]',
    'label :: .text-\\[24px\\]',
    'select-name :: select',
  ],
  '390x812|light|done': [
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .mt-\\[2px\\].w-\\[22px\\].h-\\[22px\\]',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .mt-\\[2px\\].w-\\[22px\\].h-\\[22px\\]',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(7) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(9) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .w-\\[46px\\]',
    'color-contrast :: .gap-1.py-1.transition-colors:nth-child(1) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .gap-1.py-1.transition-colors:nth-child(2) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .gap-1.py-1.transition-colors:nth-child(3) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .items-start.gap-2.flex > .leading-relaxed.break-words.py-0\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .mt-1.flex-wrap.gap-2 > .text-\\[11\\.5px\\].text-fg-meta.gap-1\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .items-start.gap-2.flex > .leading-relaxed.break-words.py-0\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .mt-1.flex-wrap.gap-2 > .text-\\[11\\.5px\\].text-fg-meta.gap-1\\.5',
    'label :: .text-\\[24px\\]',
    'select-name :: select',
  ],
  '390x812|light|today': [
    'button-name :: .overflow-hidden.rounded-2xl.relative:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(7) > .mb-6.justify-between.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(9) > .mb-6.justify-between.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .w-\\[46px\\]',
    'button-name :: section:nth-child(1) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'button-name :: section:nth-child(2) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'button-name :: section:nth-child(3) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'color-contrast :: .gap-1.flex-col.flex > .text-\\[12px\\].text-slate-400.font-medium',
    'color-contrast :: .line-through.text-blue-400.opacity-70',
    'color-contrast :: .overflow-hidden.rounded-2xl.relative:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-rose-300\\/90.bg-rose-500\\/10.px-1\\.5',
    'color-contrast :: .overflow-hidden.rounded-2xl.relative:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: .overflow-hidden.rounded-2xl.relative:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-rose-300\\/90.bg-rose-500\\/10.px-1\\.5',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(2) > .text-\\[11px\\].text-fg-faint.tracking-tight',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(3) > .text-\\[11px\\].text-fg-faint.tracking-tight',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(4) > .text-\\[11px\\].text-fg-faint.tracking-tight',
    'color-contrast :: .text-primary\\/80',
    'color-contrast :: .text-slate-200',
    'color-contrast :: section:nth-child(1) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: section:nth-child(1) > .mb-3.gap-2\\.5.items-center > .items-baseline.gap-2\\.5.flex > .text-\\[12px\\].text-slate-400.font-medium',
    'color-contrast :: section:nth-child(2) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: section:nth-child(2) > .mb-3.gap-2\\.5.items-center > .items-baseline.gap-2\\.5.flex > .text-\\[12px\\].text-slate-400.font-medium',
    'label :: .text-\\[24px\\]',
    'select-name :: select',
  ],
  '430x812|dark|all': [
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface-overlay.border-edge.p-4 > .items-start.gap-3.flex > .border-primary.mt-\\[2px\\].w-\\[22px\\]',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .bg-surface-overlay.border-edge.p-4 > .items-start.gap-3.flex > .border-primary.mt-\\[2px\\].w-\\[22px\\]',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(3) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(4) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(7) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(9) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .w-\\[46px\\]',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface-overlay.border-edge.p-4 > .items-start.gap-3.flex > .opacity-50.min-w-0.flex-1 > .items-start.gap-2.flex > .text-slate-400.decoration-slate-500.line-through',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface-overlay.border-edge.p-4 > .items-start.gap-3.flex > .opacity-50.min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(1) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(3) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(4) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .text-fg-disabled',
    'color-contrast :: .text-primary.tracking-tight.text-\\[11px\\]',
    'color-contrast :: .text-primary\\/80',
    'label :: .\\[color-scheme\\:dark\\]',
    'label :: .text-\\[24px\\]',
    'select-name :: select',
  ],
  '430x812|dark|done': [
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .mt-\\[2px\\].w-\\[22px\\].h-\\[22px\\]',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .mt-\\[2px\\].w-\\[22px\\].h-\\[22px\\]',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(7) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(9) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .w-\\[46px\\]',
    'color-contrast :: .gap-1.py-1.transition-colors:nth-child(1) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .gap-1.py-1.transition-colors:nth-child(2) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .gap-1.py-1.transition-colors:nth-child(3) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .items-start.gap-2.flex > .leading-relaxed.break-words.py-0\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .mt-1.flex-wrap.gap-2 > .text-\\[11\\.5px\\].text-fg-meta.gap-1\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .items-start.gap-2.flex > .leading-relaxed.break-words.py-0\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .mt-1.flex-wrap.gap-2 > .text-\\[11\\.5px\\].text-fg-meta.gap-1\\.5',
    'color-contrast :: .text-primary.tracking-tight.text-\\[11px\\]',
    'label :: .text-\\[24px\\]',
    'select-name :: select',
  ],
  '430x812|dark|today': [
    'button-name :: .overflow-hidden.rounded-2xl.relative:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(7) > .mb-6.justify-between.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(9) > .mb-6.justify-between.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .w-\\[46px\\]',
    'button-name :: section:nth-child(1) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'button-name :: section:nth-child(2) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'button-name :: section:nth-child(3) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'color-contrast :: .line-through.text-blue-400.opacity-70',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(2) > .text-\\[11px\\].text-fg-faint.tracking-tight',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(3) > .text-\\[11px\\].text-fg-faint.tracking-tight',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(4) > .text-\\[11px\\].text-fg-faint.tracking-tight',
    'color-contrast :: .text-primary.text-\\[11px\\].tracking-tight',
    'color-contrast :: .text-primary\\/80',
    'label :: .text-\\[24px\\]',
    'select-name :: select',
  ],
  '430x812|light|all': [
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface-overlay.border-edge.p-4 > .items-start.gap-3.flex > .border-primary.mt-\\[2px\\].w-\\[22px\\]',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .bg-surface-overlay.border-edge.p-4 > .items-start.gap-3.flex > .border-primary.mt-\\[2px\\].w-\\[22px\\]',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(3) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(4) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .border-2.hover\\:border-primary\\/70.border-edge-strong',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(7) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(9) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .w-\\[46px\\]',
    'color-contrast :: .group\\/ci.text-left.gap-2:nth-child(1) > .text-fg-meta.text-\\[11\\.5px\\].leading-relaxed',
    'color-contrast :: .line-clamp-2',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface-overlay.border-edge.p-4 > .items-start.gap-3.flex > .opacity-50.min-w-0.flex-1 > .items-start.gap-2.flex > .text-slate-400.decoration-slate-500.line-through',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface-overlay.border-edge.p-4 > .items-start.gap-3.flex > .opacity-50.min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-rose-300\\/90.bg-rose-500\\/10.text-\\[10px\\]',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-rose-300\\/90.bg-rose-500\\/10.text-\\[10px\\]',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(3) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(4) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(1) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(3) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(4) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .text-fg-disabled',
    'color-contrast :: .text-primary\\/80',
    'label :: .\\[color-scheme\\:dark\\]',
    'label :: .text-\\[24px\\]',
    'select-name :: select',
  ],
  '430x812|light|done': [
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .mt-\\[2px\\].w-\\[22px\\].h-\\[22px\\]',
    'button-name :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .mt-\\[2px\\].w-\\[22px\\].h-\\[22px\\]',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(7) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(9) > .justify-between.mb-6.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .w-\\[46px\\]',
    'color-contrast :: .gap-1.py-1.transition-colors:nth-child(1) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .gap-1.py-1.transition-colors:nth-child(2) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .gap-1.py-1.transition-colors:nth-child(3) > .tracking-tight.text-\\[11px\\].text-fg-faint',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .items-start.gap-2.flex > .leading-relaxed.break-words.py-0\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(1) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .mt-1.flex-wrap.gap-2 > .text-\\[11\\.5px\\].text-fg-meta.gap-1\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .items-start.gap-2.flex > .leading-relaxed.break-words.py-0\\.5',
    'color-contrast :: .overflow-hidden.relative.rounded-2xl:nth-child(2) > .border-edge.bg-surface-overlay.p-4 > .items-start.gap-3.flex > .min-w-0.opacity-50.flex-1 > .mt-1.flex-wrap.gap-2 > .text-\\[11\\.5px\\].text-fg-meta.gap-1\\.5',
    'label :: .text-\\[24px\\]',
    'select-name :: select',
  ],
  '430x812|light|today': [
    'button-name :: .overflow-hidden.rounded-2xl.relative:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(7) > .mb-6.justify-between.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .shadow-2xl.rounded-t-\\[2rem\\].p-6:nth-child(9) > .mb-6.justify-between.items-center > .p-1.text-fg-muted.hover\\:text-fg',
    'button-name :: .w-\\[46px\\]',
    'button-name :: section:nth-child(1) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'button-name :: section:nth-child(2) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'button-name :: section:nth-child(3) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .mt-\\[2px\\].hover\\:border-primary\\/70.w-\\[22px\\]',
    'color-contrast :: .gap-1.flex-col.flex > .text-\\[12px\\].text-slate-400.font-medium',
    'color-contrast :: .group\\/ci.text-left.gap-2:nth-child(1) > .text-fg-meta.text-\\[11\\.5px\\].leading-relaxed',
    'color-contrast :: .line-through.text-blue-400.opacity-70',
    'color-contrast :: .overflow-hidden.rounded-2xl.relative:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-rose-300\\/90.bg-rose-500\\/10.px-1\\.5',
    'color-contrast :: .overflow-hidden.rounded-2xl.relative:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: .overflow-hidden.rounded-2xl.relative:nth-child(2) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-rose-300\\/90.bg-rose-500\\/10.px-1\\.5',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(2) > .text-\\[11px\\].text-fg-faint.tracking-tight',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(3) > .text-\\[11px\\].text-fg-faint.tracking-tight',
    'color-contrast :: .py-1.gap-1.transition-colors:nth-child(4) > .text-\\[11px\\].text-fg-faint.tracking-tight',
    'color-contrast :: .text-primary\\/80',
    'color-contrast :: .text-slate-200',
    'color-contrast :: section:nth-child(1) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative:nth-child(1) > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: section:nth-child(1) > .mb-3.gap-2\\.5.items-center > .items-baseline.gap-2\\.5.flex > .text-\\[12px\\].text-slate-400.font-medium',
    'color-contrast :: section:nth-child(2) > .gap-2\\.5.flex-col.flex > .overflow-hidden.rounded-2xl.relative > .bg-surface.active\\:border-primary\\/30.border-edge > .items-start.gap-3.flex > .min-w-0.flex-1 > .mt-1.flex-wrap.gap-2 > .text-fg-meta.text-\\[11\\.5px\\].gap-1\\.5',
    'color-contrast :: section:nth-child(2) > .mb-3.gap-2\\.5.items-center > .items-baseline.gap-2\\.5.flex > .text-\\[12px\\].text-slate-400.font-medium',
    'label :: .text-\\[24px\\]',
    'select-name :: select',
  ],
};
